### ISSUE TITLE
I'm Not dead

### ISSUE THREAD

**Issue by Colonizor48** [Apple0726/helixteus-3#3]
Hi its colonizor48. Remember me from discord? I'm kinda not on there anymore but i still wana help with hx3. I also have hx2 and 1 archived for when flash goes offline. I kinda dont know godot but i will help with suggestions.

**Comment by Colonizor48** [comment]
I would suggest using hx2 sprites as placeholders to make the game look a bit more professional. If u dont have them anymore i can try to rip them from my copy of hx2.

**Comment by Apple0726** [comment]
Hi, yes I do remember you, but the fact that you're not on Discord anymore means you're kinda missing out on a lot of things, there are interesting discussions about the game from time to time. That said, if you want to replace the placeholders with HX2 sprites go ahead! I could do it myself but I'm kinda lazy and want to focus on more important things for now.

**Comment by Colonizor48** [comment]
Anyway i just wanted to say i am very very hyped for this. This has the potential to be a steam worthy game. Never give up.

**Comment by Colonizor48** [comment]
I would say take insperation from grand strategy games. I would recommend trying to combine an idle and 4x/grand strategy game as hx2 had elements of 4x strategy which were probably my favorite part of the game.
