### ISSUE TITLE
Cannot play ship speedup minigame.

### ISSUE THREAD

**Issue by Colonizor48** [Apple0726/helixteus-3#44]
It says click anywhere to continue, but clicking does nothing.

**Comment by Colonizor48** [comment]
Log:
[godot.log](https://github.com/Apple0726/helixteus-3/files/12839698/godot.log)

**Comment by Colonizor48** [comment]
In the meantime is there a way I could hack to bypass the tutorial?

**Comment by Apple0726** [comment]
Sorry for the late reply, it will be fixed right about now!
